### ISSUE TITLE
How is boost_rate used?

### ISSUE THREAD

**Issue by haichaoyu** [sbadirli/GrowNet#3]
Hello,

Thanks for the interesting work. One question about the [dynamic boost rate](https://github.com/sbadirli/GrowNet/blob/master/Classification/main_cls_cv.py#L182) in each epoch. Is it really used in ensemble network forwarding?

**Comment by sbadirli** [comment]
Hi Haichao,

Thanks for your interest in the Grownet. Yes, it is. If you check the boost
rate you may see how it is updated in each stage. Why did you ask? If you
have a question regarding the specific part of the algorithm, please let me
know, I will check on it.

Best,
Sarkhan

**Comment by sbadirli** [comment]
Hey,

Since you did not mention any comments, I am closing the issue.

Best,
Sarkhan
