### ISSUE TITLE
Regarding NDCG Gain used in the results for ranking

### ISSUE THREAD

**Issue by sdeepaknarayanan** [sbadirli/GrowNet#5]
Hi,

I was wondering what gains of NDCG you'd used for ranking results in your Arxiv version of the paper. Did you use identity gain, or exp2 gain? Wouldn't both have different effects on performance, and finally test results?

**Comment by sbadirli** [comment]
Hey Deepak,

I used identity gain, the same type that XGBoost paper used. 
And of course, they would have different effects. Results with exp2 gain will be slightly lower as you would expect.

**Comment by sdeepaknarayanan** [comment]
Hey @sbadirli, thanks for the quick reply. 

I was just wondering if you had tried with the other way of computing the gains for NDCG, and if so, if you could share any results you may have on them for XgBoost and Grownet? Do you still find GrowNet to be consistently better than XgBoost in that case as well?

Thanks!

**Comment by sbadirli** [comment]
Unfortunately do not have that comparison.
You can get the results with exp gain for Grownet by simply changing
gain_type in the main function. For XGBoost I never tried it with exp gain
as I was using their own NDCG loss implementation which is identity. For
XGBoost you may use my code for exp gain on XGBoost results.

Best,
Sarkhan

**Comment by sdeepaknarayanan** [comment]
Hi Sarkhan,

Thanks a lot for confirming the same. I'll do as per your suggestion. 

Closing this issue.
